### ISSUE TITLE
New features review tracking issue (WIP)

### ISSUE THREAD

**Issue by avive** [spacemeshos/local-testnet#31]
# Readme / Docs
1. Add dependencies min version. e.g. docker, npm, etc...
1. And link to CLIWallet releases and explain that a version of CLIWallet that works with the localnet node version needs to be used. For example: https://github.com/spacemeshos/cli-wallet/releases/
1. Need instructions regarding to view the logs of a miner in the network. User should be able to pipe to tail any node logs or to open any node log file from terminal.
1. Need instructions on how to connect a CLIWallet to any of the network nodes GRPC services endpoint. e.g. host + port in CLIWallet params. User should be able to connect an instance of CLIWallet to the API of any of the nodes on the network. CLIWallet accepts host::port startup flags.
1. Well-known working configs: Add a section with a set of configs that should work which contain: 1. link to a node release. 1. link to a config file. 1. link to a CLIWallet release.

# Config
Minor issue:  --coinbase <string> - param should be a standard sm account address in the form of 0x[20 hex chars] and not a full public key, or call it --coinbase-key and leave public key param. It is confusing because in node --coinbase accepts an address.

**Comment by lrettig** [comment]
Seconded on the logging question. Of course this is trivial to do with `docker ps` and `docker logs <container id>` but it would be really nice if the CLI output these instructions, along with a list of docker container IDs for each node. Better yet, add a `--log` command that lets you view (or tail) the logs of one or more nodes in realtime.

**Comment by avive** [comment]
The current CLI is just a runner that creates and runs a network - it doesn't support commands for a running testnet so I'd like to close this issue because it is now documented and easy to view the logs via docker or the terminal - I've added this to the docks: http://localhost:3000/#/localnet. @lrettig
